apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-exporter-config
  namespace: monitoring
data:
  conf.yaml: |
    # MQTT All values default to paho.mqtt.client defaults
    mqtt:
      host:      '10.0.1.10'
      port:       30083

    metrics:
      - name:     'icu_room101_heartrate'
        help:     'Topic icu/room101/heartrate'
        type:     'gauge'
        topic:    'icu/room101/heartrate'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'icu_room101_spo2'
        help:     'Topic icu/room101/spo2'
        type:     'gauge'
        topic:    'icu/room101/spo2'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'icu_room101_pump'
        help:     'Topic icu/room101/pump'
        type:     'gauge'
        topic:    'icu/room101/pump'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'icu_room102_heartrate'
        help:     'Topic icu/room102/heartrate'
        type:     'gauge'
        topic:    'icu/room102/heartrate'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'icu_room102_spo2'
        help:     'Topic icu/room102/spo2'
        type:     'gauge'
        topic:    'icu/room102/spo2'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'icu_room102_pump'
        help:     'Topic icu/room102/pump'
        type:     'gauge'
        topic:    'icu/room102/pump'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'

      - name:     'icu_nursestation_alarm'
        help:     'Topic icu/nursestation/alarm'
        type:     'gauge'
        topic:    'icu/nursestation/alarm'
        label_configs:
          - source_labels:  ['__msg_topic__']           # Required (when label_configs is present)
            separator:      '/'                         # Optional default ';'
            regex:          '(.*)'                      # Optional default '(.*)'
            target_label:   '__topic__'                 # Required (when label_configs is present and 'action' = 'replace')
            replacement:    '\1'                        # Optional default '\1'
            action:         'replace'                   # Optional default 'replace'
