apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  prometheus.rules: |-
    groups:
    - name: Alert-Rule 1 - Fog overload offloading
      interval: 1s
      rules:
      - alert: Rule 1 - Fog overload offloading
        # Condition for alerting
        expr: 100 - (avg by(node_hostname) (rate(node_cpu_seconds_total{mode="idle",node_hostname="fog-icu"}[35s])) * 100) > 80
        for: 1m
        annotations:
          adaptations: '{"offloading_0.2810918860067402":{"pod_name":"c4","image":"mosquitto:2.0","namespace":"default","requirements":{"memory":"700M","cpu":"700m"},"volumes":[{"name":"mosquitto-config","mountPath":" /config/mqtt.conf","subPath":"mosquitto.conf"}],"hosts":{"node":{"operator":"In","values":["edge-icu102"]},"region":{"operator":"In","values":["ICU Wing"]},"cluster":{"operator":"In","values":[]}}},"scaling_0.38508871849051274":{"instances":2,"image":"hospital/alert-service:latest","namespace":"default","requirements":{"memory":"700M","cpu":"700m"},"volumes":[],"hosts":{"node":{"operator":"In","values":[]},"region":{"operator":"In","values":["Hospital"]},"cluster":{"operator":"In","values":[]}}}}'
        labels:
          severity: 'critical'
          actions: '1'

    - name: Alert-Rule 2 - Tachycardia alert
      interval: 1s
      rules:
      - alert: Rule 2 - Tachycardia alert
        # Condition for alerting
        expr: icu_room101_heartrate > 120 or icu_room102_heartrate > 120
        for: 5s
        annotations:
          adaptations: '{"operate_actuator_0.767814987991025":{"broker_ip":"10.0.1.10","port":30083,"topic":"icu/nursestation/alarm","message":"On"}}'
        labels:
          severity: 'critical'
          actions: 'all'
